import { NextRequest, NextResponse } from "next/server"
import { auth } from "@/lib/auth"
import { execute } from "@/lib/db"
import { rawMaterials } from "@/lib/queries/raw-materials"
import { PMMaterials } from "@/lib/queries/product-materials"

// ─── Param builders ──────────────────────────────────────────────────────────

/**
 * Maps request body to the ordered parameter array expected by rawMaterials.insert.
 * Order: [rm_code, name, make, type, uom, status, hsn_code, inci_name]
 */
function toRmParams(b: any) {
  return [
    null,                          // rm_code — auto-generated by the DB
    b.name.trim(),
    b.make?.trim() || null,
    b.type?.trim() || null,
    b.uom?.trim() || null,
    b.status || "active",
    b.hsn_code?.trim() || null,
    b.inci_name?.trim() || null,
  ]
}

/**
 * Maps request body to the ordered parameter array expected by PMMaterials.insert.
 * Order: [pm_code, name, type, hsn_code, uom, status]
 */
function toPmParams(b: any) {
  return [
    null,                          // pm_code — auto-generated by the DB
    b.name.trim(),
    b.type?.trim() || null,
    b.hsn_code?.trim() || null,
    b.uom?.trim() || null,
    b.status || "active",
  ]
}

// ─── Route handler ───────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  // Reject unauthenticated requests.
  const session = await auth()
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const body = await req.json()
  const { action, material } = body

  // ── Create a base material record (no vendor / manufacturer rates) ──────────
  // Body: { action: "create", material: "rm" | "pm", ...fields }
  if (action === "create") {

    if (material === "rm") {
      // Validate required RM fields.
      const {name , make, inci_name} = body;
      if (!name?.trim())       return NextResponse.json({ error: "Name is required." }, { status: 400 })
      if (!make?.trim())       return NextResponse.json({ error: "Make is required." }, { status: 400 })
      if (!inci_name?.trim())  return NextResponse.json({ error: "INCI Name is required." }, { status: 400 })
      
      // Dublicate check
      try {
        const check = await execute(rawMaterials.checkDuplicate , [name , make, inci_name] );
        if(check) {
          return NextResponse.json({ error: "A raw material with this code already exists." }, { status: 409 })
        }
      }catch(e) {
        return NextResponse.json({error:"Error while dublicate check: " , e} , {status: 409});
      }
      try {
        const result = await execute(rawMaterials.insert, toRmParams(body))
        return NextResponse.json({ id: result.insertId })
      } catch (err: any) {
        // Unique constraint on rm_code (null here, so unlikely — but handle it).
        if (err.code === "ER_DUP_ENTRY") {
          return NextResponse.json({ error: "A raw material with this code already exists." }, { status: 409 })
        }
        console.error("Material master RM create error:", err)
        return NextResponse.json({ error: "Database error: " + err.message }, { status: 500 })
      }
    }

    if (material === "pm") {

      const {name , type} = body;
      // Validate required PM fields.
      if (!name?.trim())  return NextResponse.json({ error: "Name is required." }, { status: 400 })
      if (!type?.trim())  return NextResponse.json({ error: "Type is required." }, { status: 400 })
      
        try {
          const check = await execute(PMMaterials.checkDuplicate , [name, type])
          if(check) {
            return NextResponse.json({ error: "A Packing material with this code already exists.", check }, { status: 409 })
          }

        }catch(e) {
          return NextResponse.json({error: "Error Occured while ckecking dublicate: " , e} , {status: 409})
        }


      try {
        const result = await execute(PMMaterials.insert, toPmParams(body))
        return NextResponse.json({ id: result.insertId })
      } catch (err: any) {
        if (err.code === "ER_DUP_ENTRY") {
          return NextResponse.json({ error: "A packing material with this code already exists." , }, { status: 409 })
        }
        console.error("Material master PM create error:", err)
        return NextResponse.json({ error: "Database error: " + err.message }, { status: 500 })
      }
    }

    // material value was neither "rm" nor "pm".
    return NextResponse.json({ error: 'material must be "rm" or "pm".' }, { status: 400 })
  }

  return NextResponse.json({ error: "Invalid action." }, { status: 400 })
}
